### ISSUE TITLE
Request: Include `XDG_BIN_HOME`

### ISSUE THREAD

**Issue by Samueru-sama** [marcoradocchia/microxdg#1]
As the title says, add the option to check for `$XDG_BIN_HOME` and if it is not defined a default of `$HOME/.local/bin` is returned.

While `XDG_BIN_HOME` is not technically in the spec, [it is used by thousands of applications already](https://github.com/search?q=XDG_BIN_HOME&type=code), is [mentioned on the NixOS wiki](https://nixos.wiki/wiki/Environment_variables) and used in [other xdg libraries](https://github.com/adrg/xdg/blob/master/paths_unix_test.go#L55-L59).

**Comment by marcoradocchia** [comment]
Thank you for your issue. It has been addressed in #2, so I'm going to close it. If you have further requests, let me know!
